
# conda_env.yaml
name: fairness_tutorial
dependencies:
  - python=3.6
  - pandas>=0.20
  - numpy=1.*
  - scikit-learn
  - jupyter
  - graphviz
  - seaborn
  - pip
  - pathlib
  - conda-forge::notebook
  - pip:
    # pip packages unavailable in conda
    - aequitas
